In [174]:
import pandas as pd
import numpy as np
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import train_test_split

#Importando o modelo machine learnig
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier

In [175]:
# importar csv
data = pd.read_csv("nge_dados_input.csv")


In [176]:
data.dtypes

id              int64
entidade        int64
fornecedor      int64
complexidade    int64
stat_pagto      int64
qtd_pag_word    int64
qtd_carc        int64
qtd_tabela      int64
qtd_image       int64
pag_final       int64
dtype: object

In [177]:
data.columns

Index(['id', 'entidade', 'fornecedor', 'complexidade', 'stat_pagto',
       'qtd_pag_word', 'qtd_carc', 'qtd_tabela', 'qtd_image', 'pag_final'],
      dtype='object')

In [178]:
# prepara dados de entrada X e dados de saida Y
colunas_X= ['entidade', 'fornecedor', 'complexidade', 'stat_pagto',
       'qtd_pag_word', 'qtd_carc', 'qtd_tabela',
       'qtd_image']
colunas_y=['pag_final']
#colunas_y=['id',  'pag_final']

X = data[colunas_X]
y = data[colunas_y]

In [179]:
X.tail()

entidade  fornecedor  complexidade  stat_pagto  qtd_pag_word  qtd_carc  \
88         0           0             2           0            24     32209   
89         0           0             2           0            24     32209   
90         0           0             1           0            59    125372   
91         0           0             1           0            48     83759   
92         2           1             1           0           100     75298   

    qtd_tabela  qtd_image  
88          21         17  
89           7          8  
90         363        323  
91         115        205  
92         132        224

In [234]:
data

id  entidade  fornecedor  complexidade  stat_pagto  qtd_pag_word  \
0   224323         0           0             1           0            87   
1   224325         0           0             1           0            82   
2   225392         0           0             3           0            41   
3   225392         0           0             3           0            41   
4   225531         0           0             2           0            36   
..     ...       ...         ...           ...         ...           ...   
88  235502         0           0             2           0            24   
89  235502         0           0             2           0            24   
90  235519         0           0             1           0            59   
91  235512         0           0             1           0            48   
92  233900         2           1             1           0           100   

    qtd_carc  qtd_tabela  qtd_image  pag_final  
0     124996         470        685        140  
1     116747          76         94        122  
2      42460          28         24         52  
3      64070         397        639         52  
4      39371         233        397         48  
..       ...         ...        ...        ...  
88     32209          21         17         36  
89     32209           7          8         36  
90    125372         363        323         78  
91     83759         115        205         66  
92     75298         132        224         82  

[93 rows x 10 columns]

In [180]:
y.head()

pag_final
0        140
1        122
2         52
3         52
4         48

In [181]:
#########################################################
# INÍCIO DA PARTE DE MACHINE LEARNIG  \
# RANDOM FOREST
########################################################

In [182]:
# instalar biblioteca scikit-learn
#! pip install -U scikit-learn

In [202]:
# método train_test_split, Scikit-Learn 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=42)

In [203]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((83, 8), (10, 8), (83, 1), (10, 1))

In [204]:
y_test.head()

pag_final
40        340
22         98
55         34
72         38
0         140

In [205]:
modelo = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
modelo.fit(X_train, y_train)

<ipython-input-205-957cc5138365>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  modelo.fit(X_train, y_train)


RandomForestClassifier(n_jobs=-1, random_state=0)

In [206]:
p = modelo.predict(X_test)

In [207]:
p

array([122, 110,  40,  28, 126,  68,  48,  20,  46, 100])

In [208]:
print(p.shape,y_test.shape)

(10,) (10, 1)


In [209]:
y_test

pag_final
40        340
22         98
55         34
72         38
0         140
26         72
39         42
67         22
10         40
44         98

In [210]:
# https://github.com/WalnerPessoa/Medical-Cost-Personal/blob/master/Aula%205%20-%20Regress%C3%A3o%20linear%20para%20prever%20as%20despesas%20m%C3%A9dicas%20de%20um%20paciente%20.ipynb


# Criando uma lista com os nomes dos atributos
#feature_cols = ['age','sex','bmi','children','smoker']

# Usando a lista para escolher um subconjunto do dataframe original
#X = data[feature_cols]

# Selecionando a Série no dataframe
#y = data.charges

# Dividindo entre conjunto de treinamento e teste
#X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Ajsutando o modelo (Aprendendo os coeficientes)
#linreg.fit(X_train, y_train)

# Fazendo predições no conjunto de teste
#y_pred = linreg.predict(X_test)

# Calculando RMSE para nossas predições
#print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

In [211]:
#########################################################
# INÍCIO DA PARTE DE MACHINE LEARNIG  \
# LINEAR REGRESSION
########################################################

In [212]:
# prepara dados de entrada X e dados de saida Y
colunas_X= [ 'entidade', 'fornecedor', 'complexidade', 'stat_pagto',
       'qtd_pag_word',  'qtd_carc', 'qtd_tabela',
       'qtd_image']
colunas_y=['pag_final']
X = data[colunas_X]
y = data[colunas_y]

In [213]:
# método train_test_split, Scikit-Learn 
X_train, X_test, y_train, y_test = train_test_split(X, y,  test_size=0.10,random_state=1)

In [214]:
##### machine learnig

#Instanciando o estimador
linreg = LinearRegression()

#Ajustando o modelo ao conjunto de treino
linreg.fit(X_train, y_train)

#Interpretando os coeficientes do modelo
#Visualizando a interseção e os coeficientes 
print(linreg.intercept_)
print(linreg.coef_)


[33.92361313]
[[-3.82023801e+00 -2.08621493e+01 -1.09833828e+01  1.65845115e-12
   7.11322794e-01  2.36430856e-04  2.78209498e-02 -2.25224125e-02]]


In [215]:
colunas_X

['entidade',
 'fornecedor',
 'complexidade',
 'stat_pagto',
 'qtd_pag_word',
 'qtd_carc',
 'qtd_tabela',
 'qtd_image']

In [216]:
X_train.columns

Index(['entidade', 'fornecedor', 'complexidade', 'stat_pagto', 'qtd_pag_word',
       'qtd_carc', 'qtd_tabela', 'qtd_image'],
      dtype='object')

In [217]:
#Atributos e seus coeficientes
list(zip(colunas_X, linreg.coef_))

[('entidade',
  array([-3.82023801e+00, -2.08621493e+01, -1.09833828e+01,  1.65845115e-12,
          7.11322794e-01,  2.36430856e-04,  2.78209498e-02, -2.25224125e-02]))]

In [218]:
#Fazendo predições no conjunto de teste
y_pred = linreg.predict(X_test)

In [219]:
y_pred

array([[ 36.45729881],
       [ 67.36877289],
       [117.74715014],
       [ 53.7512613 ],
       [ 36.84515494],
       [ 86.45799465],
       [ 74.99338876],
       [153.10768881],
       [ 69.78911106],
       [ 45.94946962]])

In [220]:
y_test

pag_final
59         52
74         68
44         98
56         48
88         36
77         86
62         68
53        126
54         68
39         42

In [232]:
# codigos consultados de 
# https://github.com/WalnerPessoa/Medical-Cost-Personal/blob/master/Aula%205%20-%20Regress%C3%A3o%20linear%20para%20prever%20as%20despesas%20m%C3%A9dicas%20de%20um%20paciente%20.ipynb


# calculando a media de um exemplo
# Definindo os valores de resposta verdadeiros e preditos
true = [100,50,30,30]
pred = [90,50,50,30]
print("dados verdadeiros: ",true)
print("dados inferidos:", pred)
# Calculando erro médio absoluto na mão
print('erro médio absoluto: ',(10+0+20+0)/4)
# Calculando erro médio absoluto utilizando scikit-learn
from sklearn import metrics
print('erro médio absoluto: ',metrics.mean_absolute_error(true,pred)) 

#Calculando MSE na mão
print('MSE: ',(10**2+0+20**2+0)/4)
# Calculando MSE utilizando scikit-learn
print('MSE: ',metrics.mean_squared_error(true,pred))

# Calculando RMSE na mão
print('RMSE: ',np.sqrt((10**2+0+20**2+0)/4))
# Calculando RMSE utilizando scikit-learn
print('RMSE: ',np.sqrt(metrics.mean_squared_error(true,pred)))

dados verdadeiros:  [100, 50, 30, 30]
dados inferidos: [90, 50, 50, 30]
erro médio absoluto:  7.5
erro médio absoluto:  7.5
MSE:  125.0
MSE:  125.0
RMSE:  11.180339887498949
RMSE:  11.180339887498949


Comparando essas métricas:

- MAE é a mais fácil de entender.
- MSE é mais popular que MAE, porque MSE "pune" erros grandes.
- RMSE é ainda mais popular que MSE, porque RMSE é interpretável na mesma unidade de y.

In [230]:
#Nós precisamos de uma métrica de avaliação para comparar nossas predições com os valores verdadeiros!

# Calculando RMSE utilizando scikit-learn
print('RMSE: ',np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

RMSE:  12.11799697428631


In [229]:
#Como interpretar esse valor?
# numero menor de RMSE é melhor
