In [104]:
import pandas as pd
import numpy as np
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import train_test_split

#Importando o modelo machine learnig
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier

In [105]:
# importar csv
data = pd.read_csv("nge_dados_input.csv")


In [106]:
data.columns

Index(['id', 'entidade', 'fornecedor', 'complexidade', 'stat_pagto',
       'qtd_pag_word', 'qtd_pag_estimado', 'qtd_carc', 'qtd_tabela',
       'qtd_image', 'pag_final'],
      dtype='object')

In [118]:
# prepara dados de entrada X e dados de saida Y
colunas_X= ['entidade', 'fornecedor', 'complexidade', 'stat_pagto',
       'qtd_pag_word', 'qtd_pag_estimado', 'qtd_carc', 'qtd_tabela',
       'qtd_image']
colunas_y=['pag_final']
#colunas_y=['id',  'pag_final']

X = data[colunas_X]
y = data[colunas_y]

In [119]:
X.tail()

entidade  fornecedor  complexidade  stat_pagto  qtd_pag_word  \
29         0           0             0           0            77   
30         0           0             1           0            24   
31         0           0             0           0            59   
32         0           0             0           0            48   
33         2           1             0           0           100   

    qtd_pag_estimado  qtd_carc  qtd_tabela  qtd_image  
29               120     33684         383        348  
30                48     32209           7          8  
31                90    125372         363        323  
32                75     83759         115        205  
33               120     75298         132        224

In [120]:
y.head()

pag_final
0          1
1         52
2         66
3         86
4         68

In [121]:
#########################################################
# INÍCIO DA PARTE DE MACHINE LEARNIG  \
# RANDOM FOREST
########################################################

In [122]:
# instalar biblioteca scikit-learn
#! pip install -U scikit-learn

In [123]:
# método train_test_split, Scikit-Learn 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [124]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((27, 9), (7, 9), (27, 1), (7, 1))

In [125]:
y_test.head()

pag_final
15         88
19         86
27         54
26         84
8          30

In [126]:
modelo = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
modelo.fit(X_train, y_train)

<ipython-input-126-957cc5138365>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  modelo.fit(X_train, y_train)


RandomForestClassifier(n_jobs=-1, random_state=0)

In [127]:
p = modelo.predict(X_test)

In [128]:
p

array([84, 68, 52, 78, 30, 84, 78])

In [129]:
print(p.shape,y_test.shape)

(7,) (7, 1)


In [130]:
y_test

pag_final
15         88
19         86
27         54
26         84
8          30
24         82
21        108

In [ ]:
# https://github.com/WalnerPessoa/Medical-Cost-Personal/blob/master/Aula%205%20-%20Regress%C3%A3o%20linear%20para%20prever%20as%20despesas%20m%C3%A9dicas%20de%20um%20paciente%20.ipynb


# Criando uma lista com os nomes dos atributos
#feature_cols = ['age','sex','bmi','children','smoker']

# Usando a lista para escolher um subconjunto do dataframe original
#X = data[feature_cols]

# Selecionando a Série no dataframe
#y = data.charges

# Dividindo entre conjunto de treinamento e teste
#X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Ajsutando o modelo (Aprendendo os coeficientes)
#linreg.fit(X_train, y_train)

# Fazendo predições no conjunto de teste
#y_pred = linreg.predict(X_test)

# Calculando RMSE para nossas predições
#print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

In [ ]:
#########################################################
# INÍCIO DA PARTE DE MACHINE LEARNIG  \
# LINEAR REGRESSION
########################################################

In [131]:
# prepara dados de entrada X e dados de saida Y
colunas_X= [ 'entidade', 'fornecedor', 'complexidade', 'stat_pagto',
       'qtd_pag_word', 'qtd_pag_estimado', 'qtd_carc', 'qtd_tabela',
       'qtd_image']
colunas_y=['pag_final']
X = data[colunas_X]
y = data[colunas_y]

In [136]:
# método train_test_split, Scikit-Learn 
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [137]:
##### machine learnig

#Instanciando o estimador
linreg = LinearRegression()

#Ajustando o modelo ao conjunto de treino
linreg.fit(X_train, y_train)
print(linreg.intercept_)
print(linreg.coef_)


[-1.28808384]
[[-1.10722425e+00 -1.92264346e+01 -2.92104819e+00  2.48689958e-14
  -1.83904747e-02  8.79118250e-01  3.84322408e-05  1.69309247e-03
  -9.12292294e-03]]


In [138]:
colunas_X

['entidade',
 'fornecedor',
 'complexidade',
 'stat_pagto',
 'qtd_pag_word',
 'qtd_pag_estimado',
 'qtd_carc',
 'qtd_tabela',
 'qtd_image']

In [139]:
X_train.columns

Index(['entidade', 'fornecedor', 'complexidade', 'stat_pagto', 'qtd_pag_word',
       'qtd_pag_estimado', 'qtd_carc', 'qtd_tabela', 'qtd_image'],
      dtype='object')

In [140]:
#Atributos e seus coeficientes
list(zip(colunas_X, linreg.coef_))

[('entidade',
  array([-1.10722425e+00, -1.92264346e+01, -2.92104819e+00,  2.48689958e-14,
         -1.83904747e-02,  8.79118250e-01,  3.84322408e-05,  1.69309247e-03,
         -9.12292294e-03]))]

In [141]:
#Fazendo predições no conjunto de teste
y_pred = linreg.predict(X_test)

In [142]:
y_pred

array([[ 33.37861581],
       [ 87.00133864],
       [ 94.94695324],
       [ 54.29221826],
       [ 65.30659464],
       [ 73.31593219],
       [ 61.88888929],
       [119.46946354],
       [114.12711002]])

In [143]:
y_test

pag_final
14         38
19         86
3          86
27         54
32         66
26         84
20         68
25         84
24         82